[package]
name = "mees-proc"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.10", features = ["full"] }
quote = "1.0.26"
proc-macro2 = { version = "1.0.54", features = ["span-locations"] }
